In [4]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

In [5]:
##!pip install joblib

In [18]:
class Perceptron():
    def __init__(self, eta: float=None, epochs : int=None):
        self.weights = np.random.randn(3) * 1e-4 ## Always keep the weights small so that it takes less time to train.
        self.eta = eta ## learning rate
        self.epochs = epochs ## iterations 
        
        
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias : \n{X_with_bias}")

In [33]:
obj = Perceptron(eta = 0.01, epochs=10)
obj.eta

0.01

In [34]:
obj.epochs

10

In [35]:
obj.weights

array([-3.69518792e-05,  2.00702974e-04,  5.82837327e-05])

In [38]:
y = np.ones((4,2))
y

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
obj.fit(X,y)

X with bias : 
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]
